#!/bin/bash

# Determine working directory
install_dir=$(dirname $0)

# Distribute the script if Firefox is already installed
if [ -d "$3/Applications/Firefox.app/Contents/Resources" ]; then

# Create distribution directory
mkdir "$3/Applications/Firefox.app/Contents/Resources/distribution/"

# Copy policies.json
cp ${install_dir}/"autoconfig.js" "$3/Applications/Firefox.app/Contents/Resources/distribution/"

fi

exit 0
